title: Einfach Satt
description: persönliche Sammlung leckerer Rezepte
copyright: https://github.com/skoenig/kochbuch
languageCode: de
languageName: Deutsch
displayName: DE
isoCode: de
weight: 1
rtl: false
dateFormat: 2\. January 2006
