# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme: fire
defaultAppearance: light
autoSwitchAppearance: true
showAppearanceSwitcher: false
enableSearch: true
enableCodeCopy: false
showScrollToTop: true
homepage:
  layout: page
  showRecent: false
article:
  showDate: true
  showDateUpdated: false
  showAuthor: false
  showBreadcrumbs: true
  showDraftLabel: true
  showEdit: false
  editAppendPath: true
  showHeadingAnchors: true
  showPagination: false
  invertPagination: false
  showReadingTime: false
  showTableOfContents: false
  showTaxonomies: true
  showWordCount: false
list:
  showBreadcrumbs: false
  showSummary: false
  showTableOfContents: false
  groupByYear: false
sitemap:
  excludedKinds:
    - taxonomy
    - term
taxonomy:
  showTermCount: true
